# Generated by Django 5.0.4 on 2024-04-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=350)),
                ('location', models.CharField(max_length=350)),
                ('name', models.CharField(max_length=350)),
                ('phoneNumber', models.CharField(max_length=350)),
                ('crimeType', models.CharField(max_length=350)),
            ],
        ),
        migrations.DeleteModel(
            name='MapItem',
        ),
    ]
